# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mvn package
    docker build -t myapp:01 .
    docker tag myapp:01 tamajitacr.azurecr.io/myapp:01
    echo FgEuRWrDvTRYxJ8afaWjTlghkcEH3uz+| docker login tamajitacr.azurecr.io  --username tamajitacr --password-stdin
    docker push tamajitacr.azurecr.io/myapp:01
  displayName: 'Run a multi-line script'
